// ============================================================================
// THE SINGLE COMPONENT THAT CHANGES WHEN AKAHU FULL APP IS APPROVED
// ============================================================================
//
// Today, this app has an Akahu Personal App: it can read the developer's
// own connected accounts via a static User Access Token generated by hand
// at my.akahu.nz, but has no App Secret, no OAuth endpoints, and no
// multi-user support (see Akahu's docs on Personal vs Full Apps).
//
// Every other file in this integration — akahu-client.ts (calling Akahu's
// REST API), the connect_bank_account / get_bank_connection_token /
// record_bank_sync / disconnect_bank_connection SQL functions, and the
// Next.js UI/actions — only ever deals in an opaque "token" string. None
// of them know or care how that token was obtained. That's deliberate:
// it means the Personal-App-vs-OAuth distinction is contained entirely to
// this one file.
//
// To migrate once Full App is approved:
//   1. Implement OAuthAkahuAuthProvider.acquireToken() below: redirect to
//      Akahu's /authorize endpoint, exchange the returned `code` for a
//      token via POST https://api.akahu.io/v1/token using AKAHU_APP_SECRET.
//   2. Set the AKAHU_AUTH_MODE Edge Function secret to "oauth".
//   3. Add AKAHU_APP_SECRET as an Edge Function secret.
//   4. Update the "Connect bank" UI (app/(app)/settings/banks) to redirect
//      to Akahu instead of showing the paste-a-token form — this is a UI
//      change, not a change to any of the sync/disconnect/data code.
// Nothing else needs to change.
// ============================================================================

export interface AkahuAuthProvider {
  readonly mode: "personal" | "oauth";
  acquireToken(input: Record<string, unknown>): Promise<string>;
}

class PersonalAppAuthProvider implements AkahuAuthProvider {
  readonly mode = "personal" as const;

  async acquireToken(input: { pastedToken?: unknown }): Promise<string> {
    if (typeof input.pastedToken !== "string" || input.pastedToken.trim().length === 0) {
      throw new Error("missing_token");
    }
    return input.pastedToken.trim();
  }
}

class OAuthAkahuAuthProvider implements AkahuAuthProvider {
  readonly mode = "oauth" as const;

  async acquireToken(): Promise<string> {
    // Not implemented yet — requires a Full Akahu App. See the migration
    // notes at the top of this file.
    throw new Error("oauth_not_configured");
  }
}

export function getAkahuAuthProvider(): AkahuAuthProvider {
  const mode = Deno.env.get("AKAHU_AUTH_MODE") ?? "personal";
  return mode === "oauth" ? new OAuthAkahuAuthProvider() : new PersonalAppAuthProvider();
}
